import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#adabaa",
        "on-primary-fixed": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#ffffff",
        "tertiary-container": "#737575",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#454747",
        tertiary: "#3a3c3c",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3c3b3b",
        "on-secondary-fixed": "#1c1b1b",
        "on-background": "#1a1c1c",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#5e5e5e",
        "surface-container-highest": "#e2e2e2",
        error: "#ba1a1a",
        background: "#f9f9f9",
        "surface-container-low": "#f3f3f4",
        "surface-dim": "#dadada",
        "surface-container": "#eeeeee",
        "secondary-container": "#d6d4d3",
        "on-secondary-container": "#1c1b1b",
        "outline-variant": "#c6c6c6",
        "on-surface-variant": "#474747",
        "error-container": "#ffdad6",
        surface: "#f9f9f9",
        "on-tertiary": "#e2e2e2",
        outline: "#777777",
        "on-primary": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#5d5f5f",
        "on-surface": "#1a1c1c",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "on-tertiary-fixed": "#ffffff",
        "inverse-surface": "#2f3131",
        "primary-container": "#3b3b3b",
        "on-error": "#ffffff",
        "on-error-container": "#410002",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#5e5e5e",
        secondary: "#5f5e5e",
        primary: "#000000",
        "on-primary-fixed-variant": "#e2e2e2",
        "secondary-fixed": "#c8c6c5",
        "primary-fixed-dim": "#474747",
      },
      borderRadius: {
        DEFAULT: "0rem",
        none: "0rem",
        sm: "0rem",
        md: "0rem",
        lg: "0rem",
        xl: "0rem",
        "2xl": "0rem",
        "3xl": "0rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
